# Generated by Django 3.1.3 on 2021-05-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('openPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('prevPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('volume', models.IntegerField()),
                ('value', models.IntegerField()),
                ('marketCap', models.IntegerField()),
                ('peRatio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pbRatio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('roe', models.DecimalField(decimal_places=2, max_digits=7)),
                ('eps', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dividendYield', models.DecimalField(decimal_places=2, max_digits=7)),
                ('industryPE', models.DecimalField(decimal_places=2, max_digits=7)),
                ('bookValue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('todayslow', models.DecimalField(decimal_places=2, max_digits=7)),
                ('todayshigh', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
