# Generated by Django 3.1.3 on 2021-05-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('returns', models.DecimalField(decimal_places=2, max_digits=7)),
                ('returnsThree', models.DecimalField(decimal_places=2, max_digits=7)),
                ('returnsFive', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.DecimalField(decimal_places=2, max_digits=7)),
                ('categoryThree', models.DecimalField(decimal_places=2, max_digits=7)),
                ('categoryFive', models.DecimalField(decimal_places=2, max_digits=7)),
                ('risk', models.CharField(max_length=30)),
                ('minSIP', models.IntegerField()),
                ('expenseRatio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('nav', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fundStarted', models.DateField()),
                ('fundSize', models.IntegerField()),
            ],
        ),
    ]
