# Generated by Django 3.1.3 on 2021-05-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stocks_founded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='founded',
            field=models.IntegerField(),
        ),
    ]
